#ifndef __APP_FLASH_H__
#define __APP_FLASH_H__

#define APP_FLASH_IR_SECTOR_1							(0x0000)
#define APP_FLASH_IR_SECTOR_2							(0x1000)

#define APP_FLASH_AK_DBG_FATAL_LOG_SECTOR				(0x2000)
#define APP_FLASH_AK_DBG_IRQ_LOG_SECTOR					(0x3000)
#define APP_FLASH_AK_DBG_MSG_SECTOR_1					(0x4000)
#define APP_FLASH_AK_DBG_MSG_SECTOR_2					(0x5000)

#define APP_FLASH_FIRMWARE_INFO_SECTOR_1				(0x6000)

#define APP_FLASH_INTTERNAL_SHARE_DATA_SECTOR_1			(0x7000)

#define APP_FLASH_DUMP_RAM_START_ADDR					(0x20000)

#define APP_FLASH_FIRMWARE_START_ADDR					(0x80000)
#define APP_FLASH_FIRMWARE_BLOCK_64K_SIZE				(2)

#endif //__APP_FLASH_H__
